<?php defined('BASEPATH') OR exit('No direct script access allowed');
/**
 * CodeIgniter PDF Library
 *
 * Generate PDF's in your CodeIgniter applications.
 *
 * @package			CodeIgniter
 * @subpackage		Libraries
 * @category		Libraries
 * @author			Chris Harvey
 * @license			MIT License
 * @link			https://github.com/chrisnharvey/CodeIgniter-PDF-Generator-Library
 */

//require_once(dirname(__FILE__) . '/dompdf/dompdf_config.inc.php');
require_once(dirname(__FILE__) . '/dompdf/autoload.inc.php');
use Dompdf\Dompdf;

class Pdf extends DOMPDF
{	
	/**
	 * Get an instance of CodeIgniter
	 *
	 * @access	protected
	 * @return	void
	 */
	protected function ci()
	{
		return get_instance();
	}

	/**
	 * Load a CodeIgniter view into domPDF
	 *
	 * @access	public
	 * @param	string	$view The view to load
	 * @param	array	$data The view data
	 * @return	void
	 */
	public function load_view($view, $data = array())
	{
		$html = $this->ci()->load->view($view, $data, TRUE);
		//________page layouts_________

		//$this->setPaper('A4','Landscape');
		$page_orientation = $this->getPaperOrientation();

		//________font style__________
		$font = $this->getFontMetrics()->get_font("helvetica");

		//________page number__________
		if ($page_orientation == "portrait") {
			$this->getCanvas()->page_text(530, 770, "Page: {PAGE_NUM} of {PAGE_COUNT}", $font, 8, array(0,0,0));
		}elseif ($page_orientation == "Landscape") {
			$this->getCanvas()->page_text(0, 0, "Page: {PAGE_NUM} of {PAGE_COUNT}", $font, 10, array(0,0,0));
		}

		$this->getCanvas()->page_text(50, 770, "Date: ".date("Y-m-j, g:i a")." - Generated By: ".$_SESSION['name'], $font, 8, array(0,0,0));

		//_________________water mark___________________
		// $color = array(10,100,20);
		// $watermark = $this->getCanvas()->open_object();
		// $w = $this->getCanvas()->get_width();
  // 		$h = $this->getCanvas()->get_height();
  // 		$this->getCanvas()->page_text(200, $h - 340, "GSIMS", $font,110, array(0.85, 0.85, 0.85),$color, 0, -40);
  // 		$this->getCanvas()->close_object();
  //  		$this->getCanvas()->add_object($watermark, 'all');

		//____________Some other information_____________
		// $this->add_info(array(
		//'Title'=> 'Fee Defaulters',
		//'Subject'=>'subject',
		//'Author'=>'company name / department',
		//'Keywords'=>'tag1, tag2, tag3'
		//));
		$this->load_html($html);
	}
}
