<style>

.heading_s{

text-align: center; font-size: 16px;    text-decoration: underline;

}
.text_style{
	    font-size: 12px;
    font-weight: bold;
}

.border_right{
 padding: 3px;
border-right: 1px solid black;
}


.border_left{
 padding: 3px;
border-left: 1px solid black;
}



.border_top{
 padding: 3px;
border-top: 1px solid black;
}


.border_bottom{
 padding: 3px;
border-bottom: 1px solid black;
}

.border_div{
 padding: 0px;
   border: 1px solid black;
}



</style>
<?php
if($this->session->flashdata('club_updated')){
echo '<div align="center">
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">�</button>
        '.$this->session->flashdata('club_updated').'
    </div>
</div>';
}

?>


<div class="row">


<div class="col-md-4 col-lg-4 col-sm-4 border_div">
<table  width="100%" >
<tr>
<td class="text_style border_bottom " colspan="2" >
	<table>
		<tr>
		<td class="text_style" ><img height="70" width="70" src="<?php echo display_link($query_ary[0]['school_logo'],'') ?>" /></td>

<td class="text_style " class="heading_s" ><strong><?php
 echo $query_ary[0]['school_name'];



  ?></strong></td>
		</tr>
	</table>
</td>
</tr>
<tr>
<td class="text_style border_bottom border_right " ><?php echo

'Copy Detail';

?></td>
<td class="text_style border_bottom " >srn no : <?php echo $query_ary[0]['chalan_form_number'];  ?></td>
</tr>
<tr>
<td class="text_style border_bottom" colspan="2"><?php
 echo $query_ary[0]['school_bank_detail']; ?></td>
</tr>
<tr>
<td class="text_style border_bottom" colspan="2"> Department - class -  Section</td>
</tr>
<tr>
<td class="text_style border_bottom" colspan="2">
<?php echo $query_ary[0]['section'].'-'.$query_ary[0]['class'].'-'.$query_ary[0]['department']; ?>
</td>
</tr>
<tr>
<td class="text_style border_bottom  border_right" colspan="2">

<?php
$student_name=$query_ary[0]['student_name'];
$father_name=$query_ary[0]['father_name'];

echo "Father Name :".$student_name.' '.'student name'.' '.$parent_name;

?></td>

</tr>
<tr>
<td class="text_style border_bottom" colspan="2">Issue Date : <?php// echo $issue_date= $query_ary[0]['issue_date'];
?>
	/
	Due Date :

	<?php //echo date('Y-m-d', strtotime($issue_date.$query_ary[0]['due_days']));
	?>

</td>

</tr>
<table width="100%" >

<tr id="chalan" >
<td class="text_style  border_bottom border_right" width="7%">s.n</td>
<td class="text_style  border_bottom border_right" width="72%">particulars</td>
<td class="text_style  border_bottom" width="20px">Amount</td>
</tr>


</table>
</table>
<br />

Principal Signature :__________________________
<br />
<br />
<?php





 $admin_req1=get_user_info($query_ary[0]['issued_by']);  ?>


 <span>Issued By: <?php echo  $admin_req1[0]['name']; ?></span>

<br />
<img style="padding-left: 5px; " src="<?php echo  display_link($query_ary[0]['bar_code'],'student'); ?>">


</div>
<!-- yes  -->

<div class="col-md-8 col-lg-8 col-sm-8">








<h3>Student Detail</h3>




<table class="table table-hover table-responsive table-stripped">

	<tr>
		<th>Name</th><td> <?php echo student_detail($query_ary[0]['student_id']); ?></td>


	</tr>


	<tr>
		<th>Generated By</th><td> <?php

$user_req=get_user_info($query_ary[0]['generated_by']);

 echo  $user_req[0]['name']; ?></td>


	</tr>



	<tr>
		<th>Generated Date</th><td> <?php echo $query_ary[0]['generation_date']; ?></td>


	</tr>



	<tr>
		<th>Approved By</th><td> <?php

$user_req=get_user_info($query_ary[0]['approved_by']);

 echo  $user_req[0]['name']; ?></td>


	</tr>




	<tr>
		<th>Approval Date</th><td><?php echo $query_ary[0]['approval_date']; ?></td>


	</tr>



	<tr>
		<th>Issued By</th><td> <?php

$user_req=get_user_info($query_ary[0]['issued_by']);

 echo  $user_req[0]['name']; ?></td>


	</tr>











	<tr>
		<th>Issue Date</th><td> <?php echo $query_ary[0]['issue_date']; ?> </td>


	</tr>










	<tr>
		<th>Recieved By</th><td><?php

$user_req=get_user_info($query_ary[0]['received_by']);

 echo  $user_req[0]['name']; ?> </td>


	</tr>










	<tr>
		<th>Recieval Date</th><td> <?php echo $query_ary[0]['received_date']; ?></td>


	</tr>










	<tr>
		<th>Payment Date</th><td><?php echo $query_ary[0]['payment_date']; ?> </td>


	</tr>










	<tr>
		<th>Paid Amount</th><td>  <?php echo $query_ary[0]['received_amount']; ?></td>


	</tr>











</table>








<?php if($query_ary[0]['status']<=3){ ?>




<br />

 <?php echo form_open(base_url().'class_chalan_form/save_chalan_form/' , array('id'=>'save_chalan_form_id','class' => 'form-horizontal form-groups-bordered validate', 'enctype' => 'multipart/form-data'));?>



<span>Select Status : </span>
<span>

<select class="form-control" name="status">


<?php


echo student_form_status($query_ary[0]['status']); ?>

</select>


</span>
<span>comment : </span>

<span><textarea class="form-control" name="comment"><?php echo $query_ary[0]['comment'];  ?></textarea></span>
<input type="hidden" name="s_c_f_id"  value="<?php echo $query_ary[0]['s_c_f_id'];  ?>"/>



<button type="submit" class="btn btn-primary">Save</button>

 <?php  echo form_close();  ?>



</div>

<?php
}
 if($query_ary[0]['status']==3){ ?>
<div class="btn btn-primary" id="buttonLogin">Issue chalan</div>

<div class="col-md-8 col-lg-8 col-sm-8 hide_div" id="login_Box_Div">
 <?php echo form_open(base_url().'class_chalan_form/save_print_chalan/' , array('class' => 'form-horizontal form-groups-bordered validate', 'enctype' => 'multipart/form-data'));?>

<div class="col-md-5 col-lg-5 col-sm-5|">
Issue Date
</div>
<div class="col-md-7 col-lg-7  col-sm-7">
<input type="hidden" name="s_c_f_id"  value="<?php echo $query_ary[0]['s_c_f_id'];  ?>"/>
<input type="hidden" name="student_id"  value="<?php echo $query_ary[0]['student_id'];  ?>"/>

<input class="form-control " readonly="" name="issue_date" value="<?php
 echo $date= date('Y-m-d H:i:s');
?>"/>
</div>
<div class="col-md-5 col-lg-5 col-sm-5|">
Due Date
</div>
<div class="col-md-7 col-lg-7  col-sm-7">
<input class="form-control datepicker"  name="due_date" value="<?php
$days=$query_ary[0]['due_days'];
echo $date= date('m/d/Y', strtotime('+'.$days.' days'));
?>" required=""/>
<input type="hidden" class="form-control"  name="form_type"
value="<?php
echo $query_ary[0]['form_type'];
?>" required=""/>
</div>
<div class="col-md-7 col-lg-7  col-sm-7">
<button class="btn btn-primary" type="submit" >Issue</button>
</div>
<?php echo form_close();?>
</div>
<?php }
 if($query_ary[0]['status']==4){ ?>
<div class="btn btn-primary" id="button">Recieve Chalan</div>

<div class="col-md-8 col-lg-8 col-sm-8 hide_div" id="login_Box">

 <?php echo form_open(base_url().'class_chalan_form/student_chalan_payment/' , array('class' => 'form-horizontal form-groups-bordered validate', 'enctype' => 'multipart/form-data'));?>
<div class="col-md-5 col-lg-5 col-sm-5|">
Payment Amount :
</div>

<div class="col-md-7 col-lg-7  col-sm-7">

<input type="hidden" name="s_c_f_id"  value="<?php echo $query_ary[0]['s_c_f_id'];  ?>"/>

<input type="hidden" name="student_id"  value="<?php echo $query_ary[0]['student_id'];  ?>"/>

<input type="text" class="form-control " name="received_amount" value="" required=""/>


<input type="hidden" class="form-control"  name="form_type"
value="<?php
echo $query_ary[0]['form_type'];
?>" required=""/>




</div>
<div class="col-md-5 col-lg-5 col-sm-5|">
Payment Date :
</div>

<div class="col-md-7 col-lg-7  col-sm-7">
<input class="form-control datepicker" name="payment_date" value="" required=""/>
</div>

<div class="col-md-7 col-lg-7  col-sm-7">

<button class="btn btn-primary" type="submit" >Recieve</button>
</div>

 <?php echo form_close();?>
</div>



<?php } ?>
</div>

<?php

if($query_ary[0]['form_type']>2){

	$url_r=base_url().'c_student/student_information';

}else{
	$url_r=base_url().'c_student/student_pending';
}


 ?>

<a href="<?php echo $url_r; ?>" class="btn btn-primary">Back To Listing</a>


<?php

if($query_ary[0]['status']==5 || $query_ary[0]['status']==4){



 ?>

<a class="btn btn-primary" href="<?php echo base_url(); ?>class_chalan_form/view_print_chalan/<?php echo  $query_ary[0]['s_c_f_id']; ?>/<?php echo $query_ary[0]['form_type'];  ?>"  >

<?php echo get_phrase('Print_chalan_form'); ?>
</a>

<?php } ?>




<script>
$(document).ready(function(){

get_student_chalan();



$('#delete_link').click(function(e){
	e.preventDefault();

	var s_c_d_id=$(this).attr('href');
	$('#modal-4').modal('toggle');
	$.ajax({
			type: 'POST',
			data: {s_c_d_id:s_c_d_id},
			 url: "<?php echo base_url();?>class_chalan_form/delete_chalan_detail",
			dataType: "html",
			success: function(response) {
				get_student_chalan();
			}
		});








});



$('#buttonLogin').on('click', function(e){

    $("#login_Box_Div").toggle();
    $(this).toggleClass('class1');
});


$('#button').on('click', function(e){

    $("#login_Box").toggle();
    $(this).toggleClass('class1');
});






    /* submit save chalan form start */
     $('#challlan_form_save').submit(function()
     {
         if ($("#challlan_form_save").valid())
         {
           // alert('hi');
            // $(this).find(':submit').attr('disabled','disabled');
            // $(this).css( 'cursor', 'not-allowed' );
            // alert('Edited');
         }
     });
     /* submit save chalan form End*/


});

function get_student_chalan(){


			$("#loading").remove();
		$(".s_chalan").each(function(){

				$(this).remove();

			});


			$("#chalan").after("<div id='loading' class='loader'></div>")



	var s_c_f_id="<?php echo $query_ary[0]['s_c_f_id']; ?>";
	var status="<?php echo $query_ary[0]['status']; ?>";


	$.ajax({
			type: 'POST',
			data: {s_c_f_id:s_c_f_id,status:status},
			 url: "<?php echo base_url();?>class_chalan_form/get_student_chalan",
			dataType: "html",
			success: function(response) {
			$("#loading").remove();
			$("#chalan").after(response);


			}
		});




}









</script>
<style>
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid blue;
  border-right: 16px solid green;
  border-bottom: 16px solid red;
  border-left: 16px solid pink;
  width: 100px;
  height: 100px;
      margin-left: auto;
    margin-right: auto;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 1s linear infinite;
}


.loader_small {
  border: 5px solid #f3f3f3;
  border-radius: 50%;
  border-top: 5px solid blue;
  border-right: 5px solid green;
  border-bottom: 5px solid red;
  border-left: 5px solid pink;
  width: 20px;
  height: 20px;
      margin-left: auto;
    margin-right: auto;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 1s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
.hide_div{

	display: none;



}
</style>